src/Entity/Proyecto.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;


/**
 * @ORM\Entity(repositoryClass="App\Repository\ProyectoRepository")
 */
class Proyecto
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $nombre;

    /**
     * @ORM\Column(type="string", length=200)
     */
    private $descripcion;

    /**
     * @ORM\Column(type="date")
     */
    private $fecha_Inicio;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $fecha_Finalizacion;

    /**
     * @ORM\Column(type="boolean")
     */
    private $top;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $imagen;

    /**
     * @ORM\OneToMany(targetEntity="Actividad",mappedBy="proyecto")
     */
    private $actividades;

    public function __construct(){

        //$this->$actividades = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNombre(): ?string
    {
        return $this->nombre;
    }

    public function setNombre(string $nombre): self
    {
        $this->nombre = $nombre;

        return $this;
    }

    public function getDescripcion(): ?string
    {
        return $this->descripcion;
    }

    public function setDescripcion(string $descripcion): self
    {
        $this->descripcion = $descripcion;

        return $this;
    }

   
    public function getFechaInicio(): ?\DateTimeInterface
    {
        
        return $this->fecha_Inicio;
    }

    public function setFechaInicio(\DateTimeInterface $fecha_Inicio): self
    {
        
        $this->fecha_Inicio = $fecha_Inicio;

        return $this;
    }

    public function getFechaFinalizacion(): ?\DateTimeInterface
    {
        
        return $this->fecha_Finalizacion;
    }

    public function setFechaFinalizacion(\DateTimeInterface $fecha_Finalizacion): self
    {
        
        $this->fecha_Finalizacion = $fecha_Finalizacion;

        return $this;
    }

    public function getTop(): ?bool
    {
        return $this->top;
    }

    public function setTop(bool $top): self
    {
        $this->top = $top;

        return $this;
    }

    public function getImagen(): ?string
    {
        return $this->imagen;
    }

    public function setImagen(string $imagen): self
    {
        $this->imagen = $imagen;

        return $this;
    }
}

src/Controller/HomeController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\Routing\Annotation\Route;
use App\Entity\Proyecto;
use App\Entity\Usuario;

class HomeController extends Controller
{

    /** 
     * @Route("/", name="index")
     */

    public function indexAction()
    {


        $proyectoRepository = $this->getDoctrine()->getRepository(Proyecto::class);
        
        $proyectos = $proyectoRepository->findByTop(true);
        
        return $this->render('home/index.html.twig',array('proyectos' => $proyectos));
        
    }


    /** 
     * @Route("/home", name="home")
     */

    public function homeAction()
    {
        
        //Capturar el repositorio de la tabla contra la BD
        $proyectoRepository = $this->getDoctrine()->getRepository(Proyecto::class);
        //Siendo la pagina principal solo mostraremos los mejores proyectos
        $proyectos = $proyectoRepository->findByTop(true);
        
        //La template index.html está encontrada en home
        
        return $this->render('home/index.html.twig',array('proyectos' => $proyectos));
        
        //return $this->render('home/index.html.twig', [    
            //'controller_name' => 'HomeController',
        //], array('proyectos'=>$proyectos));
        
    }

    /**
     *  @Route("/proyectos", name="proyectos")
     */
    public function proyectosAction()
    {

        $proyectoRepository = $this->getDoctrine()->getRepository(Proyecto::class);
        $proyectos = $proyectoRepository->findAll();

        return $this->render('home/proyectos.html.twig', 
        array('proyectos'=>$proyectos));
    
    }

    /**
     *  @Route("/proyecto/{id}", name="proyecto")
     */

    public function proyectoFunction($id = null)
    {

        if($id != null){

            $proyectoRepository = $this->getDoctrine()->getRepository(Proyecto::class);
            $proyecto = $proyectoRepository->find($id);

            return $this->render('home/proyecto.html.twig', 
            array("proyecto"=>$proyecto));
        }
        else {

            return $this->redirectToRoute('home');
        }
    }

    /**
     *  @Route("/usuarios", name="usuarios")
     */
    public function usuariosAction()
    {

        $usuarioRepository = $this->getDoctrine()->getRepository(Usuario::class);
        $usuarios = $usuarioRepository->findAll();

        return $this->render('home/usuarios.html.twig', 
        array('usuarios'=>$usuarios));
    
    }

    /**
     *  @Route("/usuario/{id}", name="usuario")
     */

    public function usuarioFunction($id = null)
    {

        if($id != null){

            $usuarioRepository = $this->getDoctrine()->getRepository(Usuario::class);
            $usuario = $usuarioRepository->find($id);

            return $this->render('home/usuario.html.twig', 
            array("usuario"=>$usuario));

        }

        else {

            return $this->redirectToRoute('home');
        }
    }
    /**
     *  @Route("/actividades/{actividad}", name="actividades")
     */

    public function actividadesFunction($actividad="tipo")
    {       

        return $this->render('home/actividades.html.twig', 
        array("actividad"=>$actividad));
    }
}

templates/home/actividades.html.twig
{% extends 'base.html.twig'%}

{% block titulo %}Actividades{% endblock %}

{% block contenido%}

    {% if actividad == 'finalizadas' %}
    <h1>Cargamos actividades finalizadas</h1>

    {% endif %}

    {% if actividad == 'ejecutadas' %}

    <h1>Cargamos actividades ejecutadas</h1>

    {% endif %}

    {% if actividad == 'inactivas' %}

    <h1>Cargamos actividades inactivas</h1>

    {% endif %}

{% endblock %}

templates/home/index.html.twig
{#ESTO ES UN COMENTARIO#}
{#Plantilla de nuestra app#}

{% extends 'base.html.twig' %}

{# TITULO #}
{% block titulo%}Pagina principal{% endblock %}

{#CONTENIDO#}
{% block contenido %}

<header>
    <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
      <ol class="carousel-indicators">
        <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
      </ol>
      <div class="carousel-inner" role="listbox">
        <!-- Slide One - Set the background image for this slide in the line below -->
        <div class="carousel-item active" style="background-image: url({{ asset('img/Home1.jpg') }})">
          <div class="carousel-caption d-none d-md-block">
            <h3>Desarrollador</h3>
            <p>Christian Camilo Riaño Vega</p>
          </div>
        </div>
        <!-- Slide Two - Set the background image for this slide in the line below -->
        <div class="carousel-item" style="background-image: url({{ asset('img/Home2.jpg') }})">
          <div class="carousel-caption d-none d-md-block">
            <h3>Título</h3>
            <p>Ingeniero de sistemas y computación </p>
          </div>
        </div>
        <!-- Slide Three - Set the background image for this slide in the line below -->
        <div class="carousel-item" style="background-image: url({{ asset('img/Home3.jpg') }})">
          <div class="carousel-caption d-none d-md-block">
            <h3>Propósito</h3>
            <p>Ingresar a la empresa OTTIS</p>
          </div>
        </div>
      </div>
      <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>
    </div>
  </header>
  <div class="container">
    <h2 class="my-4">Nuestros mejores proyectos</h2>
    <div class="row">
      {% for proyecto in proyectos %}
      <div class="col-lg-4 col-sm-6 portfolio-item">
         <div class="card h-100">
            <a href="{{path('proyecto',{'id':proyecto.id})}}"><img class="card-img-top" src="{{asset(proyectoImg~proyecto.imagen)}}" alt=""></a>
            <div class="card-body">
              <h4 class="card-title">
                <a href="{{path('proyecto',{'id':proyecto.id})}}">{{proyecto.nombre}}</a>
              </h4>
              <p class="card-text">{{proyecto.descripcion}}</p>
            </div>
          </div>
       </div>
      {% endfor %}
    </div>
  </div> 
</div>
{% endblock %}

templates/home/proyecto.html.twig
{% extends 'base.html.twig' %}
{% block titulo %}Descripción del proyecto{% endblock%}
{% block contenido %}
<div class="container">

    <!-- Page Heading/Breadcrumbs -->
    <h1 class="mt-4 mb-3">Descripción detallada del proyecto
      <small>Público</small>
    </h1>

    <!-- Portfolio Item Row -->
    <div class="row">

      <div class="col-md-8">
        <img class="img-fluid" src="{{asset(proyectoImg~proyecto.imagen)}}" alt="">
      </div>

      <div class="col-md-4">
        <h3 class="my-3">{{proyecto.nombre}}</h3>
        <p> {{proyecto.descripcion}} </p>
        <h3 class="my-3">Detalles del proyecto</h3>
        <ul>
          <li>Fecha de inicio: {{ proyecto.fechaInicio | date('Y-m-d')}}</li>
          <li>Fecha estimada de cierre: {{ proyecto.fechaFinalizacion | date('Y-m-d')}}</li>
          <h5 class="my-3">Integrantes</h5>
          <li>Pepito perez</li>
        </ul>
      </div>

    </div>
    <!-- /.row -->

    <!-- Related Projects Row -->
    <h3 class="my-4">Proyectos relacionados</h3>

    <div class="row">

      <div class="col-md-3 col-sm-6 mb-4">
        <a href="#">
          <img class="img-fluid" src="http://placehold.it/500x300" alt="">
        </a>
      </div>

      <div class="col-md-3 col-sm-6 mb-4">
        <a href="#">
          <img class="img-fluid" src="http://placehold.it/500x300" alt="">
        </a>
      </div>

      <div class="col-md-3 col-sm-6 mb-4">
        <a href="#">
          <img class="img-fluid" src="http://placehold.it/500x300" alt="">
        </a>
      </div>

      <div class="col-md-3 col-sm-6 mb-4">
        <a href="#">
          <img class="img-fluid" src="http://placehold.it/500x300" alt="">
        </a>
      </div>
    </div>
  </div>
{% endblock%}

templates/home/proyectos.html.twig
{#Plantilla de nuestra app#}

{% extends 'base.html.twig' %}

{# TITULO #}
{% block titulo%}Proyectos{% endblock %}

{#CONTENIDO#}
{% block contenido %}

<!-- Contenido de la pagina -->
<div class="container">

    <!-- Cabezero de la pagina-->
    <h1 class="mt-4 mb-3">Todos los proyectos
      <small>Público</small>
    </h1>
    
  
      <!-- Imagen del cabecero -->
    <img class="img-fluid rounded mb-4" src="{{asset('img/projects.jpg')}}" alt="">
    <div class="row">
      {% for proyecto in proyectos %}
      <div class="col-lg-4 mb-4">
        <div class="card h-100">
          <h4 class="card-header">{{proyecto.nombre}}</h4>
          <div class="card-body">
            <p class="card-text">{{proyecto.descripcion}}</p>
          </div>
          <div class="card-footer">
            <a href="{{path('proyecto',{'id':proyecto.id})}}" class="btn btn-primary"> Ver detalles</a>
          </div>
        </div>
      </div>
      {% endfor %}
  </div>
</div>
 {% endblock %}
  

templates/home/usuario.html.twig
{% extends 'base.html.twig' %}
{% block titulo %}Descripción del usuario{% endblock%}
{% block contenido %}
<div class="container">

    <!-- Page Heading/Breadcrumbs -->
    <h1 class="mt-4 mb-3">Descripción detallada del usuario
      <small>Admin</small>
    </h1>

    <!-- Portfolio Item Row -->
    <div class="row">
      <div class="col-md-4">
        <h3 class="my-3">Detalles del usuario</h3>
        <ul>
        <li>Nombre: {{(usuario.nombre)}}</li>
        <li>Apellido: {{(usuario.apellido)}}</li>
          <li>Correo electrónico: {{(usuario.correo)}}</li>
          <li>Sexo del usuario: {% if usuario.sexo=='F' %}
              Mujer
              {% else %}
                Hombre

                {% endif %}

          </li>
          <li>Rol: {% if usuario.rol == 1 %}
              Administrador
              {% elseif usuario.rol == 2 %}
              Usuario general
              {% else %}
              Auditor
              {% endif %}
                </li>
        </ul>
      </div>
    </div>

    <!-- Related Projects Row -->
    <h3 class="my-4">Proyectos relacionados</h3>

    <div class="row">

      <div class="col-md-3 col-sm-6 mb-4">
        <a href="#">
          <img class="img-fluid" src="http://placehold.it/500x300" alt="">
        </a>
      </div>

      <div class="col-md-3 col-sm-6 mb-4">
        <a href="#">
          <img class="img-fluid" src="http://placehold.it/500x300" alt="">
        </a>
      </div>

      <div class="col-md-3 col-sm-6 mb-4">
        <a href="#">
          <img class="img-fluid" src="http://placehold.it/500x300" alt="">
        </a>
      </div>

      <div class="col-md-3 col-sm-6 mb-4">
        <a href="#">
          <img class="img-fluid" src="http://placehold.it/500x300" alt="">
        </a>
      </div>
    </div>
  </div>
{% endblock%}

templates/home/usuarios.html.twig
{#Plantilla de nuestra app#}

{% extends 'base.html.twig' %}

{# TITULO #}
{% block titulo%}Todos los usuarios{% endblock %}

{#CONTENIDO#}
{% block contenido %}

<!-- Contenido de la pagina -->
<div class="container">

    <!-- Cabezero de la pagina-->
    <h1 class="mt-4 mb-3">Todos los usuarios
      <small>Admin</small>
    </h1>
    
  
      <!-- Imagen del cabecero -->
    <img class="img-fluid rounded mb-4" src="{{asset('img/projects.jpg')}}" alt="">
    <div class="row">
      {% for usuario in usuarios %}
      <div class="col-lg-4 mb-4">
        <div class="card h-100">
          <h4 class="card-header">{{(usuario.nombre)}}
            <br>{{(usuario.apellido)}}
          </h4>
          <div class="card-body">
            <p class="card-text">Rol: {% if usuario.rol == 1 %}
                Administrador
                {% elseif usuario.rol == 2 %}
                Usuario general
                {% else %}
                Auditor
                {% endif %}</p>
          </div>
          <div class="card-footer">
            <a href="{{path('usuario',{'id':usuario.id})}}" class="btn btn-primary"> Ver detalles</a>
          </div>
        </div>
      </div>
      {% endfor %}
  </div>
</div>
 {% endblock %}
  